name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: experimental
    steps:
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: northamerica-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --build-arg REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL --file Dockerfile --tag $LOUIS_REGISTRY/louis-finesse:latest
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          LOUIS_REGISTRY: ${{ secrets.LOUIS_REGISTRY }}
      - name: Push docker image
        run: docker push $LOUIS_REGISTRY/louis-finesse:latest
        env:
          LOUIS_REGISTRY: ${{ secrets.LOUIS_REGISTRY }}
      - name: Deploy to Cloud Run
        # You may pin to the exact commit or the version.
        # uses: google-github-actions/deploy-cloudrun@e62f655d5754bec48078a72edc015367b01ee97b
        uses: google-github-actions/deploy-cloudrun@v1.0.2
        with:
          # Name of the container image to deploy (e.g. gcr.io/cloudrun/hello:latest). Required if not using a service YAML.
          image: $LOUIS_REGISTRY/louis-finesse:latest
          # ID of the service or fully qualified identifier for the service. Required if not using a service YAML.
          service: louis-finesse
          # Region in which the resource can be found.
          region: ${{ secrets.GCP_CLOUDRUN_REGION }}